### ISSUE TITLE
Commissions Warning - Missing Argument

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#278]
PHP Warning: Missing argument 4 for WCV_Commission::calculate_commission(), called in /wp-content/plugins/wc-vendors/classes/class-vendors.php on line 502 and defined in /wp-content/plugins/wc-vendors/classes/class-commission.php on line 296

Reported by https://www.wcvendors.com/help/topic/php-error-2/

**Comment by digitalchild** [comment]
This has already been fixed in the latest code branch.

**Comment by brucelv** [comment]
Hello,

I'm still getting this error in WC Vendors 1.9.0 with WP 4.5.2:

```

[user@web1 html]# head wp-content/plugins/wc-vendors/changelog.txt
Changelog for WC Vendors

Version 1.9.0

* Added: Support for WooCommerce 2.6
* Added: Vendor roles filter wcvendors_vendor_roles
* Added: Product and Vendor id's to sold_by filters
* Added: Vendor Signup Filters #269
* Added: Notify Vendors Email - Add Product SKU, if set #263
* Added: New Option: Notify Vendors show Purchase Price or Commissions #253
[user@web1 html]# tail -f /var/log/nginx/site.org.error.log
2016/06/09 23:03:44 [error] 22615#0: *14650 FastCGI sent in stderr: "PHP message: PHP Warning:  Missing argument 4 for WCV_Commission::calculate_commission(), called in /var/www/site.org/html/wp-content/plugins/wc-vendors/classes/class-vendors.php on line 502 and defined in /var/www/site.org/html/wp-content/plugins/wc-vendors/classes/class-commission.php on line 296
PHP message: PHP Warning:  Missing argument 4 for WCV_Commission::calculate_commission(), called in /var/www/site.org/html/wp-content/plugins/wc-vendors/classes/class-vendors.php on line 502 and defined in /var/www/site.org/html/wp-content/plugins/wc-vendors/classes/class-commission.php on line 296" while reading response header from upstream, client: 73.126.62.232, server: site.org, request: "POST /checkout/?wc-ajax=checkout HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/site.sock:", host: "site.org", referrer: "https://site.org/checkout/"
```
